[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pyweatherfiles"
version = "0.0.0"
description = "A generator for Typical Meteorological Year (TMY) files and weather data management."
readme = "README.md"
license = "MIT"
authors = [
  { name = "Daniel Sánchez-García", email = "daniel.sanchezgarcia@uca.es" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "numpy",
    "scipy",
    "matplotlib",
    "seaborn",
    "openpyxl",
    "ladybug-core",
    "pyyaml"
]
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/termotecnia/pyweatherfiles"
"Bug Tracker" = "https://github.com/termotecnia/pyweatherfiles/issues"

[tool.setuptools.packages.find]
include = ["pyweatherfiles*"]
exclude = ["onedrive_backup*", "examples*", "analysis_scripts*"]